# ================================
# SERVER CONFIG
# ================================
server.port=8080
server.servlet.context-path=/api
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

# ================================
# DATABASE CONFIG
# ================================
spring.datasource.url=${TSMS_DATASOURCE_URL}
spring.datasource.username=${TSMS_DATASOURCE_USERNAME}
spring.datasource.password=${TSMS_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================================
# JPA / HIBERNATE
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ================================
# JWT CONFIG
# ================================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# ================================
# LOGGING
# ================================
logging.level.org.springframework.web=INFO
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ================================
# REDIS CONFIG
# ================================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.timeout=3000

# ================================
# CORS CONFIG
# ================================
cors.allowed-origins= ${CORS_ALLOWED_ORIGINS}
cors.allowed-methods= ${CORS_ALLOWED_METHODS}
cors.allowed-headers= ${CORS_ALLOWED_HEADERS}
cors.allow-credentials= ${CORS_ALLOW_CREDENTIALS}
cors.max-age= ${CORS_MAX_AGE}

# ================================
# ACCOUNT INITIALIZATION
# ================================
app.init-admin.enabled=true
app.init-admin.email=admin@e.tlu.edu.vn
app.init-admin.password=12345678

